title: "Aobzii"

owner: "Aobzii"
info: "一个记录笔记、日常碎片与漫谈的博客。"
desc: "丢失的茶叶蛋，在文字里找回。"

menu:
  日常: /daily/
  归档: /archives/
  关于: /about/

max_post: 5

tcolor: 8FCF9D

usercss: css/user.css

footer: true
github: https://github.com/Aobzii2024
outlook: mailto:aobzii2024@outlook.com
netease_music: https://music.163.com/#/user/home?id=3669845181
telegram: https://t.me/+wa2hX3Kax9BkNTVh

switch_light: ☀️
switch_dark: 🌑

picjs: /js/pic.min.js

favicon: /images/main.jpg
thumbnail: /images/main.jpg

article:
  thumbnail: true
